# Generated by Django 5.2.5 on 2025-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_phone', models.CharField(max_length=15)),
                ('employee_hire_date', models.DateField()),
                ('employee_job_title', models.CharField(max_length=100)),
            ],
        ),
    ]
